@if($isOpen)
    <div class="fixed inset-0 z-50 overflow-y-auto">
        <div class="flex min-h-screen items-center justify-center px-4 py-8">
            <div class="fixed inset-0 bg-slate-950/60"></div>
            <div class="relative z-10 w-full max-w-3xl overflow-hidden rounded-[2rem] border border-white/70 bg-white shadow-2xl dark:border-white/10 dark:bg-slate-950">
                <div class="flex items-center justify-between border-b border-slate-200 px-6 py-4 dark:border-slate-800"><div><p class="text-xs font-semibold uppercase tracking-[0.28em] text-slate-400">Campaign Builder</p><h3 class="mt-1 text-xl font-bold text-slate-900 dark:text-white">{{ $discount_id ? 'Edit discount or coupon' : 'New discount or coupon' }}</h3></div><button wire:click="$set('isOpen', false)" class="text-slate-400 transition hover:text-slate-700 dark:hover:text-slate-200"><i class="fas fa-times text-lg"></i></button></div>
                <form wire:submit.prevent="store">
                    <div class="grid max-h-[75vh] grid-cols-1 gap-5 overflow-y-auto p-6 md:grid-cols-2">
                        <div class="md:col-span-2 grid gap-3 md:grid-cols-3">
                            <button type="button" wire:click="applyPreset('welcome')" class="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-left text-sm font-semibold text-slate-700 transition hover:bg-white dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200">Welcome coupon</button>
                            <button type="button" wire:click="applyPreset('bundle')" class="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-left text-sm font-semibold text-slate-700 transition hover:bg-white dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200">Bundle saving</button>
                            <button type="button" wire:click="applyPreset('weekend')" class="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-left text-sm font-semibold text-slate-700 transition hover:bg-white dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200">Weekend countdown</button>
                        </div>
                        <div class="md:col-span-2"><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Discount name</label><input type="text" wire:model="name" placeholder="Summer Sale 20%" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-900 dark:text-white">@error('name') <span class="mt-2 block text-xs text-rose-500">{{ $message }}</span> @enderror</div>
                        <div class="md:col-span-2"><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Coupon code</label><div class="mt-2 flex gap-2"><input type="text" wire:model="code" placeholder="Leave blank to auto-apply" class="flex-1 rounded-2xl border-slate-200 font-mono uppercase text-sm shadow-none dark:border-slate-700 dark:bg-slate-900 dark:text-white"><button type="button" wire:click="generateCode" class="rounded-2xl bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-700 transition hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700">Generate</button></div>@error('code') <span class="mt-2 block text-xs text-rose-500">{{ $message }}</span> @enderror</div>
                        <div><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Type</label><select wire:model.live="type" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-900 dark:text-white"><option value="percentage">Percentage (%)</option><option value="fixed">Fixed amount (Rs)</option></select></div>
                        <div><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Value {{ $type === 'percentage' ? '(%)' : '(Rs)' }}</label><input type="number" step="0.01" min="0" wire:model="value" placeholder="{{ $type === 'percentage' ? '20' : '500' }}" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-900 dark:text-white">@error('value') <span class="mt-2 block text-xs text-rose-500">{{ $message }}</span> @enderror</div>
                        <div><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Min order amount</label><input type="number" step="0.01" min="0" wire:model="min_order_amount" placeholder="0 = no minimum" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-900 dark:text-white"></div>
                        @if($type === 'percentage')<div><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Max discount cap</label><input type="number" step="0.01" min="0" wire:model="max_discount_amount" placeholder="Leave blank = no cap" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-900 dark:text-white"></div>@endif
                        <div><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Applies to</label><select wire:model.live="scope" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-900 dark:text-white"><option value="all">All products</option><option value="category">Specific category</option><option value="product">Specific product</option></select></div>
                        @if($scope === 'category')<div><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Category</label><select wire:model="scope_id" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-900 dark:text-white"><option value="">Select category</option>@foreach($categories as $cat)<option value="{{ $cat->id }}">{{ $cat->name }}</option>@endforeach</select></div>@endif
                        @if($scope === 'product')<div><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Product</label><select wire:model="scope_id" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-900 dark:text-white"><option value="">Select product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} ({{ $product->sku }})</option>@endforeach</select></div>@endif
                        <div class="md:col-span-2 rounded-3xl border border-slate-200 bg-slate-50 p-5 dark:border-slate-800 dark:bg-slate-900"><label class="flex items-center gap-3 text-sm font-semibold text-slate-700 dark:text-slate-200"><input type="checkbox" wire:model.live="has_timer" class="rounded border-slate-300 text-amber-500">Enable countdown timer</label>@if($has_timer)<div class="mt-4 grid gap-4 md:grid-cols-2"><div><label class="text-sm font-medium text-slate-700 dark:text-slate-200">Starts at</label><input type="datetime-local" wire:model="starts_at" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-950 dark:text-white"></div><div><label class="text-sm font-medium text-slate-700 dark:text-slate-200">Ends at</label><input type="datetime-local" wire:model="ends_at" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-950 dark:text-white">@error('ends_at') <span class="mt-2 block text-xs text-rose-500">{{ $message }}</span> @enderror</div><div><label class="text-sm font-medium text-slate-700 dark:text-slate-200">Timer label</label><input type="text" wire:model="timer_label" placeholder="Sale ends in:" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-950 dark:text-white"></div><label class="flex items-center gap-3 pt-7 text-sm font-medium text-slate-700 dark:text-slate-200"><input type="checkbox" wire:model="show_timer_on_site" class="rounded border-slate-300 text-amber-500">Show countdown on site</label></div>@endif</div>
                        <div><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Usage limit</label><input type="number" wire:model="usage_limit" min="1" placeholder="Leave blank = unlimited" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-900 dark:text-white"></div>
                        <label class="flex items-center gap-3 pt-8 text-sm font-semibold text-slate-700 dark:text-slate-200"><input type="checkbox" wire:model="is_active" class="rounded border-slate-300 text-emerald-500">Active</label>
                        <div class="md:col-span-2"><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Internal notes</label><textarea wire:model="description" rows="3" placeholder="For internal reference only" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none dark:border-slate-700 dark:bg-slate-900 dark:text-white"></textarea></div>
                    </div>
                    <div class="flex justify-end gap-3 border-t border-slate-200 px-6 py-4 dark:border-slate-800"><button type="button" wire:click="$set('isOpen', false)" class="rounded-2xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-600 transition hover:bg-slate-50 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-900">Cancel</button><button type="submit" class="rounded-2xl bg-emerald-600 px-5 py-2 text-sm font-semibold text-white transition hover:bg-emerald-700">{{ $discount_id ? 'Update discount' : 'Create discount' }}</button></div>
                </form>
            </div>
        </div>
    </div>
@endif
