@if($showEditModal)
    <div class="fixed inset-0 z-50 flex items-center justify-center px-4">
        <div class="fixed inset-0 bg-slate-950/60" wire:click="$set('showEditModal', false)"></div>
        <div class="relative z-10 w-full max-w-2xl overflow-hidden rounded-[2rem] border border-white/70 bg-white shadow-2xl dark:border-white/10 dark:bg-slate-950">
            <div class="flex items-center justify-between border-b border-slate-200 px-6 py-4 dark:border-slate-800"><div><p class="text-xs font-semibold uppercase tracking-[0.28em] text-slate-400">Edit Review</p><h3 class="mt-1 text-xl font-bold text-slate-900 dark:text-white">Update moderation details</h3></div><button wire:click="$set('showEditModal', false)" class="text-slate-400 transition hover:text-slate-700 dark:hover:text-slate-200"><i class="fas fa-times text-lg"></i></button></div>
            <div class="space-y-5 p-6">
                <div><label class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">Rating</label><div class="mt-3 flex items-center gap-2">@for($i = 1; $i <= 5; $i++)<button type="button" wire:click="$set('editRating', {{ $i }})" class="text-3xl transition hover:scale-110" style="color: {{ $editRating >= $i ? '#f59e0b' : '#cbd5e1' }}">*</button>@endfor<span class="ml-2 text-sm text-slate-500 dark:text-slate-400">{{ ['', 'Poor', 'Fair', 'Good', 'Very Good', 'Excellent'][$editRating] ?? '' }}</span></div></div>
                <div><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Title</label><input wire:model="editTitle" type="text" placeholder="Review headline" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none focus:border-indigo-500 focus:ring-indigo-500 dark:border-slate-700 dark:bg-slate-900 dark:text-white">@error('editTitle') <p class="mt-2 text-xs text-rose-500">{{ $message }}</p> @enderror</div>
                <div><label class="text-sm font-semibold text-slate-700 dark:text-slate-200">Review content</label><textarea wire:model="editBody" rows="6" class="mt-2 w-full rounded-2xl border-slate-200 text-sm shadow-none focus:border-indigo-500 focus:ring-indigo-500 dark:border-slate-700 dark:bg-slate-900 dark:text-white"></textarea>@error('editBody') <p class="mt-2 text-xs text-rose-500">{{ $message }}</p> @enderror</div>
                <div class="flex items-center justify-between rounded-3xl bg-slate-50 p-4 dark:bg-slate-900"><div><p class="text-sm font-semibold text-slate-900 dark:text-white">Publish review</p><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">Customers will see it on the product page.</p></div><button wire:click="$toggle('editApproved')" class="relative inline-flex h-7 w-12 items-center rounded-full transition-colors" style="{{ $editApproved ? 'background:#4f46e5' : 'background:#cbd5e1' }}"><span class="inline-block h-5 w-5 rounded-full bg-white shadow transition-transform" style="{{ $editApproved ? 'transform:translateX(24px)' : 'transform:translateX(4px)' }}"></span></button></div>
            </div>
            <div class="flex justify-end gap-3 border-t border-slate-200 px-6 py-4 dark:border-slate-800"><button wire:click="$set('showEditModal', false)" class="rounded-2xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-600 transition hover:bg-slate-50 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-900">Cancel</button><button wire:click="saveEdit" wire:loading.attr="disabled" class="rounded-2xl bg-indigo-600 px-5 py-2 text-sm font-semibold text-white transition hover:bg-indigo-700"><span wire:loading.remove wire:target="saveEdit">Save changes</span><span wire:loading wire:target="saveEdit"><i class="fas fa-spinner fa-spin"></i> Saving</span></button></div>
        </div>
    </div>
@endif
